### ISSUE TITLE
TRestRawSignalToSignalProcess should be renamed to TRestRawSignalToDetectorSignalProcess

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/connectorslib#1]
This is to follow the same conventions as stated on the publication

**Comment by lobis** [comment]
This issue is quite old now, the process is now named `TRestRawToDetectorSignalProcess`. It was renamed at some point after this issue, even though it doesn't exactly match `TRestRawSignalToDetectorSignalProcess` (maybe it was too long).

Shall we close this issue @jgalan?
