### ISSUE TITLE
TRestDetectorSignalToRawSignalProcess problems reading parameters

### ISSUE THREAD

**Issue by DavidDiezIb** [rest-for-physics/connectorslib#30]
I'm not sure if something has changed in this process in latest versions but now I'm having problems to read parameters. Actually, the problem appears when I do not set some parameters, instead of retrieving the default one it makes stranges things. So when I launch the process I get a "bad allocation" error: 
![imagen](https://user-images.githubusercontent.com/77273709/225275992-976e94b9-a6d7-4137-b0c0-0b44eff0547b.png)

Cheking the parameters values during the data processing I realized that most of the are not correct:
![imagen](https://user-images.githubusercontent.com/77273709/225276437-25db3ca5-b080-45b5-aef6-85be2ee8f843.png)

For example, fNPoints sould be by default 512, not -1. The same happens with others. 

I can fix it locally, but doing so I realizaed that this process does more things that are not specified in the documentation. It has some sort of calibration procedure inside. I don't know if some one uses these features but I think they shouldn't be here.

**Comment by jgalan** [comment]
Please, share the means to reproduce the problem. E.g. `RML` files and `restG4` example.

**Comment by juanangp** [comment]
I believe the issue might be inside `InitFromConfigFile`, I think we should remove this function and use the one in metadata.

In general  `InitFromConfigFile` should not be ovewriten unless we introduce a complex metadata structure

**Comment by jgalan** [comment]
I created a PR removing the implementation of `InitFromConfigFile`. Perhaps, that helps to solve this issue.

However, make sure that the RML parameters comply with naming conventions of metadata members. `fCalibrationGain` --> `<parameter name="calibrationGain" ...>`

**Comment by jgalan** [comment]
https://github.com/rest-for-physics/connectorslib/pull/31

**Comment by DavidDiezIb** [comment]
> I believe the issue might be inside InitFromConfigFile

Exactly, changing few things there I avoided the problem.  
I'll check the PR and the naming conventions.

**Comment by DavidDiezIb** [comment]
Everything works fine in #31
